CONFIG_NFCT_PINS_AS_GPIOS=y

CONFIG_ZMK_POINTING=y

CONFIG_ZMK_BATTERY_REPORTING=y

# Enable RGB LED widget for battery & BLE connection status
CONFIG_RGBLED_WIDGET=y

# Battery indicator: 1s duration, green (>=50%), yellow (<50%), disable critical warning blinks
CONFIG_RGBLED_WIDGET_BATTERY_BLINK_MS=1000
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_HIGH=50
CONFIG_RGBLED_WIDGET_BATTERY_COLOR_HIGH=2
CONFIG_RGBLED_WIDGET_BATTERY_COLOR_MEDIUM=3
CONFIG_RGBLED_WIDGET_BATTERY_COLOR_LOW=3
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_CRITICAL=0

# Connection indicator: 1s duration, blue (connected), white (advertising / reset), red (disconnected)
CONFIG_RGBLED_WIDGET_CONN_BLINK_MS=1000
CONFIG_RGBLED_WIDGET_CONN_COLOR_CONNECTED=4
CONFIG_RGBLED_WIDGET_CONN_COLOR_ADVERTISING=7
CONFIG_RGBLED_WIDGET_CONN_COLOR_DISCONNECTED=1
CONFIG_RGBLED_WIDGET_CONN_SHOW_USB=y
CONFIG_RGBLED_WIDGET_CONN_COLOR_USB=6

CONFIG_ZMK_PM_SOFT_OFF=y
